kind: Pod
apiVersion: v1
metadata:
  name: pod1
  labels:   ## Mandotary
    app: mynginx
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
