kind: Pod
apiVersion: v1
metadata:
  name: mytomcatpod2
  labels:
    app: myapp
spec:
  containers:
    - name: mytomcat2
      image: tomcat:latest
      ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
    - name: mynginx2
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
