############################### Docker Swarm ##################################

version: '3.7'
volumes:
  data:
  databkp:
services:
  springboot: # Service Name, Can be any
    image: lerndevops/springboot-mongo-app:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 150Mb
    ports:
      - "9090:8080"
    depends_on:  # Springboot service depended on mongo service. So docker will deploy mongo first.
      - mongo
  mongo:  # Service Name, Can be any
    image: lerndevops/mongo:latest
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - "data:/data/db"
      - "databkp:/data/bkp"
