version: '3.7'
networks:
  mytestnet:
volumes:
  mytestvol:
services:
  mytestser:
    image: tomcat
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: 150Mb
    volumes:
      - "mytestvol:/usr/local/tomcat/webapps"
    networks:
      - mytestnet
